version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: doska_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doska_wordpress
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      # Xdebug configuration
      WORDPRESS_DEBUG: 1
      # PHP_IDE_CONFIG: serverName=doska
      XDEBUG_MODE: develop,debug
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
      XDEBUG_START_WITH_REQUEST: "yes"
      # XDEBUG_IDEKEY: doska
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: doska_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - wordpress_network

volumes:
  db_data:

networks:
  wordpress_network:
    driver: bridge

